name: publish
on: [push]
jobs:
publish-docker-image:
  runs-on: ubuntu-latest
  steps:
  - name: Checkout
    uses: actions/checkout@v2
  - name: Login to GitHub Container Registry
    uses: docker/login-action@v1
    with:
    registry: ghcr.io
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}
  - name: Build the Docker image
    run: |
        docker build . --tag ghcr.io/trickeydan/hue2mqtt-python:latest
        docker run ghcr.io/trickeydan/hue2mqtt-python:latest
        docker push ghcr.io/trickeydan/hue2mqtt-python:latest